q11:
	g++ CED19I002_q1-recursive.cpp -lglut -lGL -lGLEW -lGLU
	./a.out

q12:
	g++ CED19I002_q1-iterative.cpp -lglut -lGL -lGLEW -lGLU
	./a.out

q21:
	g++ CED19I002_q2-recursive.cpp -lglut -lGL -lGLEW -lGLU
	./a.out

q22:
	g++ CED19I002_q2-iterative.cpp -lglut -lGL -lGLEW -lGLU
	./a.out
